@file:Suppress("OPT_IN_USAGE")

import com.london.buildsrc.AppConfig
import com.london.buildsrc.configureGitHooks
import org.jetbrains.kotlin.gradle.dsl.KotlinAndroidProjectExtension

// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.compose) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.hilt) apply false
    alias(libs.plugins.jetbrains.kotlin.jvm) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.google.firebase.firebase.perf) apply false
    alias(libs.plugins.google.gms.google.services) apply false
    alias(libs.plugins.google.firebase.crashlytics) apply false
    alias(libs.plugins.kotlinx.kover)
}

subprojects {
    apply(plugin = "org.jetbrains.kotlinx.kover")

    plugins.withId("org.jetbrains.kotlin.android") {
        extensions.configure<KotlinAndroidProjectExtension> {
            compilerOptions {
                freeCompilerArgs.addAll(AppConfig.freeCompilerArgs)
            }
        }
    }

    kover {
        reports {
            filters {
                includes {
                    classes(
                        "**/*UseCase.kt",
                        "**/*ViewModel.kt",
                        "**/*RepositoryImpl.kt",
                    )
                }

                excludes {
                    annotatedBy("com.london.domain.KoverIgnore")
                    annotatedBy("*Composable")

                    classes(
                        "**.model.**",
                        "**.di.**",
                        "**.exception.**",
                        "**.exceptions.**",
                        "**.mapper.**",
                        "**.ui.**",
                        "**.entity.**",
                        "**.local.**",
                        "**.build.**",

                        "dagger.hilt.internal.aggregatedroot.codegen.*",
                        "hilt_aggregated_deps.*",
                        "*_HiltModules*",
                        "**HiltModules**",
                        "*Hilt_*",
                        "*_Factory*",
                        "*BuildConfig*",

                        "**/*_AutoGenerated*",
                        "**/*_Impl*",
                        "**/*_Binder*",
                        "**/*_Component*",

                        "*.R",
                        "*.R_*",
                        "*.BuildConfig*",
                        "*.Manifest*",
                        "*.ComposableSingletons*",
                        "*.MainActivity*",
                        "*.NovixApplication*",
                        "*.NovixApp*",
                        "com.london.designsystem*",
                        "com.london.imageharamblur*",
                        "entity.**",
                        "**.dao.**",
                        "**.dto.**",
                        "**.response.**",
                        "exceptions.**",
                    )
                }
            }

            verify {
                rule {
                    bound { minValue = 80 }
                }
            }
        }
    }
}

dependencies {
    kover(projects.domain)
    kover(projects.data)
    kover(projects.presentation)
}


configureGitHooks()
