API_KEY=""
IMAGE_URL="https://image.tmdb.org/t/p/w500"
BASE_URL="https://api.themoviedb.org/"
################
# SIGNING KEYS #
################
keyAlias=test
keyPassword=testtest
storePassword=testtest
storeFile=../testKeyStore.jks

###############
#   API URL   #
###############
api_key="150589259d5da28c67e1ffa2890204d1"
