################
# SIGNING KEYS #
################
keyAlias=test
keyPassword=testtest
storePassword=testtest
storeFile=../testKeyStore.jks

###############
#   API KEYS  #
###############
IMAGE_URL="https://image.tmdb.org/t/p/w500"
BASE_URL="https://api.themoviedb.org/"
AUTHORIZATION_KEY=""
