################
# SIGNING KEYS #
################
keyAlias=test
keyPassword=testtest
storePassword=testtest
storeFile=../testKeyStore.jks

###############
#   API URL   #
###############
API_KEY=""
IMAGE_URL="https://image.tmdb.org/t/p/w500"
BASE_URL="https://api.themoviedb.org/"
