package com.london.domain.entity.tvshowdetails

data class TvShowDetailsEntity(
    val adult: Boolean,
    val backdropPath: String?,
    val createdBy: List<TvShowCreatorEntity>,
    val episodeRunTime: List<Int>,
    val firstAirDate: String,
    val tvShowGenres: List<TvShowGenreEntity>,
    val homepage: String,
    val id: Int,
    val inProduction: Boolean,
    val languages: List<String>,
    val lastAirDate: String,
    val lastTvShowEpisodeToAir: TvShowEpisodeEntity?,
    val name: String,
    val nextTvShowEpisodeToAir: TvShowEpisodeEntity?,
    val tvShowNetworks: List<TvShowNetworkEntity>,
    val numberOfEpisodes: Int,
    val numberOfSeasons: Int,
    val originCountry: List<String>,
    val originalLanguage: String,
    val originalName: String,
    val overview: String,
    val popularity: Double,
    val posterPath: String?,
    val productionCompanies: List<TvShowProductionCompanyEntity>,
    val productionCountries: List<TvShowProductionCountryEntity>,
    val tvShowSeasons: List<TvShowSeasonEntity>,
    val tvShowSpokenLanguageEntities: List<TvShowSpokenLanguageEntity>,
    val status: String,
    val tagline: String,
    val type: String,
    val voteAverage: Double,
    val voteCount: Int
)
