name: Android CI/CD with Firebase

on:
  pull_request:
    types: [closed]
    branches: [develop]
  workflow_dispatch: # Enable Manual Execution

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    if: (github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-${{ hashFiles('**/gradle-wrapper.properties', '**/*.gradle*', '**/settings.gradle*', '**/libs.versions.toml') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-
            gradle-cache-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "api_key=\"${{ secrets.TMDB_API_KEY }}\"" >> local.properties

      - name: Decode Firebase Config
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json

      - name: Build Release APK
        run: ./gradlew -PversionCode=${{ github.run_number }} -PversionName="1.0.${{ github.run_number }}" assembleRelease

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.ACCOUNT_SERVICE_JSON }}
          groups: testers
          file: app/build/outputs/apk/release/app-release.apk
          releaseNotes: |
            New update from PR #${{ github.event.pull_request.number }}
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref_name }}
