name: Android CI/CD with Firebase

on:
  pull_request:
    types: [closed] # This specifies the action runs when a pull request is closed.
    branches: [ develop ] # This specifies the action runs only for PRs targeting the 'develop' branch.

jobs:
  build-and-deploy:
    # This 'if' condition ensures the job only runs if the pull request was actually merged.
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout code
    - name: Checkout code
      uses: actions/checkout@v4
    
    # 2. Set up Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    # 3. Set up Android SDK
    # This step is essential to download and configure the Android SDK.
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    # 4. Cache Gradle packages
    # Caching speeds up your builds by reusing downloaded libraries.
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-cache-${{ hashFiles('**/gradle-wrapper.properties', '**/*.gradle*', '**/settings.gradle*') }}
        restore-keys:
          gradle-cache-${{ runner.os }}-
          gradle-cache-
    
    # 5. Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # 6. Decode google-services.json
    - name: Decode Firebase Config
      run: |
        echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json
    
    # 7. Build the app
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    
    # 8. Deploy to Firebase App Distribution (CD part)
    - name: Deploy to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: testers
        file: app/build/outputs/apk/debug/app-debug.apk
        releaseNotes: |
          New update from PR #${{ github.event.pull_request.number }}
          Commit: ${{ github.sha }}
          Branch: ${{ github.ref_name }}
